### ISSUE TITLE
Meta-analytic t tests - mix one- and two-sample  

### ISSUE THREAD

**Issue by DominikVogel** [richarddmorey/BayesFactor#122]
`meta.ttestBF()` can be used to get a Bayes Factor for a series of "one- and two-sample designs." I assume this refers to paired and independent t-tests.

My question is if there is a way to mix t values from one-sample and two-sample designs. Let's assume I have four studies. Three of them use a two-sample design, and one uses a one-sample design. Is there a way to combine those four into a meta-analytic t test?

*P.S. I also posted the question on [StackOverflow](https://stackoverflow.com/questions/51964408/bayesian-meta-analytic-t-tests-mix-one-and-two-sample-bayesfactor). Sorry for cross-posting.*

**Comment by richarddmorey** [comment]
There's nothing that says you can't do this, but the assumption is that the (standardised) effect size is the same across all the studies. Given the differences between paired and independent designs --- the paired design is going to have less variability because the participant variability is effectively subtracted out --- this assumption is very likely to be wrong. It will lead to a misleading quantification of the evidence.

**Comment by DominikVogel** [comment]
Hi Richard,

thank you very much. I did not think about it from that perspective. Totally makes sense. 

Best,
Dominik
